# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            nxhelp.com
tagline:          'by Thomas Uhde'
description:      ''
url:              http://nxhelp.com/

author:
  name:           'Thomas Uhde'
  url:            https://twitter.com/ThomasUhde

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/acidix/nxhelp

